//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biologie.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluare
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public System.DateTime Data { get; set; }
        public int Nota { get; set; }
    }
}
