//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biologie.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string Enunt { get; set; }
        public string Varianta1 { get; set; }
        public string Varianta2 { get; set; }
        public string Varianta3 { get; set; }
        public string Varianta4 { get; set; }
        public string RaspunsCorect { get; set; }
        public int Tip { get; set; }
    }
}
