//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biologie.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FLESAR-RADU\\FLESARSQLSERVER;Initial Catalog=Database.EFBio;Integrated" +
            " Security=True")]
        public string Database_EFBioConnectionString {
            get {
                return ((string)(this["Database_EFBioConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql6004.site4now.net;Initial Catalog=DB_A36E0C_flesarradu;Persist Sec" +
            "urity Info=True;User ID=DB_A36E0C_flesarradu_admin;Password=Biologie1234")]
        public string DB_A36E0C_flesarraduConnectionString {
            get {
                return ((string)(this["DB_A36E0C_flesarraduConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql6004.site4now.net;Initial Catalog=DB_A3795C_schoolpltfmr;Persist S" +
            "ecurity Info=True;User ID=DB_A3795C_schoolpltfmr_admin;Password=Raduflesar1")]
        public string DB_A3795C_schoolpltfmrConnectionString {
            get {
                return ((string)(this["DB_A3795C_schoolpltfmrConnectionString"]));
            }
        }
    }
}
