//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biologie
{
    using System;
    using System.Collections.Generic;
    
    public partial class enunturi
    {
        public int id { get; set; }
        public int dificultate { get; set; }
        public string enunt { get; set; }
        public int tip { get; set; }
        public string raspuns { get; set; }
        public string varianta1 { get; set; }
        public string varianta2 { get; set; }
        public string varianta3 { get; set; }
        public string varianta4 { get; set; }
    }
}
