//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biologie
{
    using System;
    using System.Collections.Generic;
    
    public partial class teste
    {
        public int id { get; set; }
        public string nume { get; set; }
        public string clasa { get; set; }
        public string enunturi { get; set; }
    }
}
